import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export async function getStaticProps() {
  axios
    .get("http://localhost:3000/api/profile")
    .then((result) => console.log(result))
  return {
    props: {}
  }
}

export default function Home() {
  console.log("hello bro")
  return (
    <div className={styles.container}>
      <Head>
        <title>Dimas's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="landingPage">
        <h1>testing porto kita</h1>  
      </div>      
    </div>
  )
}
